version: '3'
services:
 docker:
  container_name: docker
  build:
   context: ./docker
   dockerfile: Dockerfile
  image: javafsd/docker
  ports:
   - "8081:8080"
 azure:
  container_name: azure
  build:
   context: ./azure
   dockerfile: Dockerfile
  image: javafsd/azure
  ports:
  - "8082:8080"